Shield Develop
eTechRacing/Shield pull request #2
Opened 2023-10-21 11:25 UTC by bernat17

Upload Altium project, schematic and blok diagram. 
Shield schematic is composed by 4 main blocks:
-Connectors. The first page of the schematic contains all signals and supplies and their interconnections with the PCB connectors.
-Supply, which uses the LV. DCDC to 5V and a LDO to reduce the 5V from de DCDC to the 3.3V for the MCU and other supply needing components.
-MCU, a STM32F7 with all connections to ports, supplies and comunications. Also includes all electronic components needed for protection and aconditioning betwheen the connector and the MCU.
-CAN comunicaction, using 2 Microchip transceivers, filters and protections. Signal from MCU is sent and recieved throught the transceiver and uses the main LEMO connector for the comunication.

2023-10-22 13:26 UTC, dweggg requested changes
Keep in mind, most of these are suggestions and not requests:


1. LV+in is only mapped to one pin, which according to DS is rated for 1A. I would suggest adding more LV+in pins (probably together) as some ECUs could deliver the power directly to heavy loads (fans, pumps, bright LEDs...). Also, fuse that connection, because as of now, there isn't any overcurrent protection to the carrier with that LV+in. It makes sense to have the 3V3 and 5V separated as they are limited to less than 1A and they need to be more accessible (but check comment nr 8!).
2. Why independent libraries? You should update the Common Files libraries with the components needed.
3. I suggest adding 2-3 user LEDs.
4. I suggest declaring certain pins to certain features (e.g ADC, SPI1/SPI2, etc.) so the SW team can always use the same pins for those. This allows for a preset pinout which makes carrier development easier. If you choose to do this, the pin names could follow an Arduino-like fashion (AN0, AN1, AN2,... DA0, DA1, DB0, DE3,...).
5. J108 is a screw terminal connector (?).
6. R202 is a THT resistor.
7. D301 & D302 seem excessive for a USB bus. 
8. Supply rails current limit should be added to the pinout so the carrier designer can make informed decisions. Also voltage ripple could be useful in the case of the 5V rail.
9. Floating GND in Supply SCH.
10. Component naming is not consistent with sheet number (Sheet 1 Supply has D201, D202, ...). I suggest renaming components in hierarchical schematic just as J1, J2... 
11. LEMO connector symbol looks different from other connectors.
12. GPIO_PE15 not mapped to connectors.
13. How do you mount the PCB? Mounting holes should be added to the SCH.
14. Surely missing decoupling to MCU. Choose a variety of capacitance values and place them in parallel, close to the voltage input of the MCU (e.g 100pF, 10nF, 100nF, 1uF, 10uF).
15. Decoupling again with U401, U402. Also, these transceivers are known to be very weak with supply transients despite the datasheet ratings, so adequate protection should be added
16.  L401, L402 have no parameters/footprint.
17. I also suggest implementing an UVLO, so the shield cannot turn on when the LV battery is below a certain voltage level.

2023-10-22 14:34 UTC, bernat17 commented
1, 3, 5, 6, 8, 9, 10, 12, 13 and 17 noted for revision.
2. Most of the components used in the SCH are still provisional and are not confirmed to be given by our sponsors. We will be updating common files repo when we recieve this confirmations.
4. As most pins can be used as GPIO and we still don't know the final purpose of each one, is decied to map them as close to the MCU as posible (pretending to avoid posible EMIs)
7. STM documentation recomends using ESD protection in the USB line. The TVS diodes used un the SCH are the ones we have avaliable now.
11. LEMO provides their own libraries for symbols and footprints. To ensure we have problems with the footprints, the LEMO libraries are the ones used in the SCH. (Will be included in common files)
14. MCU supply was made acording to STM documentation.
15. For sure we have to consider to add decoupling in U401 and U402. We are now testing this components and we have had no problems with them yet. We will study the proper value of the protection and add it to the SCH.
16. As I commented in n2, we are still waiting for confirmations from our sponsors. All footprints will be added when starting PCB design.

2023-10-22 15:56 UTC, dweggg commented
> 7. STM documentation recomends using ESD protection in the USB line. The TVS diodes used in the SCH are the ones we have avaliable now. 

These are 40V rated TVSs, very bulky and the power level you aim them to sink is way less. We used to have 6V rated TVS, which we used in CAN bus, they could be a good option. Alternatively, there are specific USB 2.0 TVS diode arrays (e.g TPD2E2U06DCKR (https://www.mouser.es/c/circuit-protection/esd-suppressors-tvs-diodes/?q=USB2.0))

> 11. LEMO provides their own libraries for symbols and footprints. To ensure we have problems with the footprints, the LEMO libraries are the ones used in the SCH. (Will be included in common files)

Good, but still suggesting a self-made symbol and footprint adaptation (check the layers used, extra silkscreen you might want to add/remove, etc.)

> 14. MCU supply was made acording to STM documentation. 

Although following DS circuits is generally a good practice, the power supply design depends heavily on the application. In an EV you will experience aggressive induced EMI at the switching frequency of the inverter and several of its harmonics. Depending on your routing/layout and wiring, you will have some parasitic inductance on your ground and your VCC. Providing low impedance paths for current at different frequencies is only achieved with multiple capacitance values. As you don't know your inductance and the specific frequency range that is going to bother you, a good measure is to fit as many values as possible, generally between 100pF to 10uF.

2023-10-23 20:09 UTC, Becato7 approved these changes

2023-11-07 17:52 UTC, eTechRacing approved these changes

2023-11-07 17:52 UTC, merged